apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: phototagacrc2cdc266add312cb93b2f9a41334.azurecr.io/app:hello
        ports:
        - containerPort: 8501
