apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: phototagacrc2cdc266add312cb93b2f9a41334.azurecr.io/app:e130b63c3f88f38e1e48d2af875c15548934160f
        ports:
        - containerPort: 8501
        env:
        - name: SUBSCRIPTION_KEY
          valueFrom:
            secretKeyRef:
              name: subscription-key
              key: subscription-key
              optional: false
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: api-url
              key: api-url
              optional: false

