apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: phototagacrc2cdc266add312cb93b2f9a41334.azurecr.io/app:13dbb2b8736380e01f2c177d2daefe0cd6821f2a
        ports:
        - containerPort: 8501
        env:
        - name: SUBSCRIPTION_KEY
          valueFrom:
            secretKeyRef:
              name: subscription-key
              key: subscription-key
              optional: false

